name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)
 
trigger: none

pr: none
 
stages:    
- stage: arm_template_deploy

  jobs:
  - job: hello_world
    pool:
      vmImage: 'ubuntu-latest'
    steps: 
    - bash: echo "Hello, from Microsoft!"

  - job: arm_template_deploy
    steps:
    - checkout: self

    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'PipelineTest'
        subscriptionId: ********'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'rg-MSSE-Pipeline'
        location: 'eastus2'
        csmFile: 'AzDO-Resource/ARM-Template/vnetTest.json'
        csmParametersFile: 'AzDO-Resource/parameters.json'
        deploymentMode: 'Incremental'
